apiVersion: v1
kind: Pod
metadata:
  name: env-pod
  namespace: secrets-demo
spec:
  containers:
    - name: secret-test
      image: nginx:latest
      #command: ['sh', '-c', 'echo "Username: $USER" "Password: $PASSWORD"']
      env:
        - name: USER
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: username.txt
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: password.txt
